name: GitHub Actions SMS on Failure Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Explicitly fail this job
        run: echo "::error file=readme.md,line=1::Missing semicolon"; exit -1
      - name: send sms if failed
        if: failure()
        run: echo "😭 something"
      - name: report success
        if: success()
        run: echo "🎉 success"
