name: GitHub Actions SMS on Failure Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: ls ${{ github.workspace }}
      - name: Explicitly fail this job
        run: exit -1
      - name: send sms if failed
        if: failure()
        run: |
          curl --verbose https://api.telekom.com/service/sms/v1/messages -H "x-api-token: ${{SMS_TOKEN}}" -d "From=${{SMS_FROM}}&To=${{SMS_TO}}&Body=Build%20failed%20on%20${{env.GITHUB_JOB}}"
      - name: report success
        if: success()
        run: echo "🎉 success"
