name: Send SMS on failure
run-name: ${{ github.actor }} wants to sent an SMS
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Explicitly fail this job
        run: exit -1
      - name: send sms if failed
        if: failure()
        run: |
          curl --verbose https://api.telekom.com/service/sms/v1/messages -H "x-api-token: ${{ secrets.SMS_TOKEN }}" -d "From=${{ secrets.SMS_FROM }}&To=${{ secrets.SMS_TO }}&Body=Build%20failed%20on%20${{ env.GITHUB_JOB }}."
      - name: report success
        if: success()
        run: echo "🎉 success"
